### ISSUE TITLE
CentOS 7.5 support

### ISSUE THREAD

**Issue by bmcustodio** [dcos/dcos-launch#175]
It would be great if the `cent-os-7-dcos-prereqs` AMI could be updated to CentOS 7.5. I have an AMI with the necessary prerequisites which I have been using to launch some clusters (`ami-03b603b2cbdd1475a` in the `us-west-2` region), but I am not sure what it would take to make a PR to this repository.

**Comment by cprovencher** [comment]
CentOS-7.4 is still what we want to prioritize in for testing and ```cent-os-7-prereqs``` is what is used in most of the CI, so we wouldn't want to change the underlying AMIs for that option. However, you can add a centos-7.5 option that would map to the AMI you have. You would need to duplicate that AMI in every region and add the option like this: https://github.com/dcos/dcos-launch/blob/master/dcos_launch/platforms/aws.py#L680

**Comment by jdef** [comment]
can this issue be closed out? AFAIK centos 7.5 is currently supported
