### ISSUE TITLE
Link to maws in README returns 404

### ISSUE THREAD

**Issue by wilsonmar** [dcos/dcos-launch#187]
In the README at https://github.com/dcos/dcos-launch 
the link "maws" requesting 
https://github.com/dcos/dcos-launch/blob/master
returns a 404. Do you mean
https://github.com/mesosphere/aws-cli

**Comment by cprovencher** [comment]
thanks - I have updated the link to point to github.com/mesosphere/maws
However that repo is only accessible to Mesosphere employees.
If you're not a Mesosphere employee, you can use any authentication method you want from the AWS documentation.
