### ISSUE TITLE
install_prereqs doesn't seem to work

### ISSUE THREAD

**Issue by bmcustodio** [dcos/dcos-launch#84]
I am using the following launch configuration to launch a CentOS-based DC/OS cluster in GCP:

```
---
launch_config_version: 1
deployment_name: bcustodio-open-centos-hyitdqfq
installer_url: https://downloads.dcos.io/dcos/stable/1.10.2/dcos_generate_config.sh
platform: gcp
provider: onprem
os_name: cent-os-7
source_image: centos-7-v20180104
image_project: centos-cloud
install_prereqs: true
machine_type: n1-standard-8
dcos_config:
    cluster_name: k8s-dev
    resolvers:
        - 169.254.169.254
    dns_search: c.massive-bliss-781.internal google.internal
    master_discovery: static
    exhibitor_storage_backend: static
    dns_forward_zones:
    - - "cluster.local"
      - - - "10.100.0.10"
          - 53
    mesos_container_log_sink: journald+logrotate
num_masters: 1
num_private_agents: 3
num_public_agents: 1
ssh_user: centos
key_helper: true
gce_zone: us-west1-b
disable_updates: true
```

The original image (`centos-7-v20180104`) doesn't include the pre-requisites and as such I am providing the `install_prereqs: true` option. However, it does not seem to work as expected:

```
[2018-01-17 19:19:36,442|dcos_launch.platforms.onprem|INFO]: Runnnig --genconf command...
docker should be installed and running. Aborting.
Traceback (most recent call last):
  File "/usr/local/bin/dcos-launch", line 9, in <module>
    load_entry_point('dcos-launch', 'console_scripts', 'dcos-launch')()
  File "/dcos-launch/dcos_launch/cli.py", line 125, in main
    return do_main(args)
  File "/dcos-launch/dcos_launch/cli.py", line 91, in do_main
    launcher.wait()
  File "/dcos-launch/dcos_launch/onprem.py", line 177, in wait
    platforms_onprem.do_genconf(t, complete_config, installer_path)
  File "/dcos-launch/dcos_launch/platforms/onprem.py", line 129, in do_genconf
    ssh_tunnel.command(['sudo', 'bash', installer_path, '--genconf'])
  File "/usr/local/lib/python3.5/dist-packages/dcos_test_utils/ssh_client.py", line 52, in command
    return subprocess.check_output(run_cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oLogLevel=ERROR', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-oControlPath=/tmp/tmp2y685j1h', '-oControlMaster=auto', '-p', '22', 'centos@35.185.228.123', 'sudo', 'bash', '/home/centos/dcos_generate_config.sh', '--genconf']' returned non-zero exit status 1
```

I tried using a custom `prereqs_script_filename` as well, but it didn't get executed. Any help would be appreciated.

**Comment by margaret** [comment]
Hi Bruno – it looks like docker is not installed on the AMI you're using, which is a prerequisite for running the dcos installer script.

https://docs.mesosphere.com/1.10/installing/oss/custom/system-requirements/#docker
https://github.com/dcos/dcos/blob/master/gen/build_deploy/bash/dcos_generate_config.sh.in#L11

I'm not sure how you are building that AMI, but if you'd like to reference how the default el7 ones are built, you can have a look in the `cloud_images` directory, e.g. https://github.com/dcos/dcos/blob/master/cloud_images/lib/el7/install_docker.sh. We have a CI job on TeamCity to build the centos images using these scripts + packer. If you have more questions feel free to ask in the tools-infra slack channel too.

**Comment by bmcustodio** [comment]
I faced this same issue today using a very similar `launch.yaml` file - shouldn't the `install_prereqs.sh` script be run _before_ checking for Docker (meaning it would install Docker itself before it is actually required)?

**Comment by margaret** [comment]
cc @cprovencher

**Comment by cprovencher** [comment]
thanks @margaret 
should get fixed by https://github.com/dcos/dcos-launch/pull/160
